#pragma once


#define RESULT_ERROR					( 0xE0000000 )
#define RESULT_FUNCTION					( 0x00100000 )



#define CSERIAL_THREAD					( 0x00010000 )
#define CSERIAL_RECV_THREAD				( 0x00020000 )



typedef enum
{
	RESULT_SUCCESS = 0x00000000,																						// 正常終了

	// CSerialThreadのエラー
	RESULT_CSERIAL_THREAD_ERROR_INIT							= (RESULT_ERROR | CSERIAL_THREAD | 0x00000001),			// 初期処理に失敗している
	RESULT_CSERIAL_THREAD_ERROR_THREAD_ALREADY_STARTED			= (RESULT_ERROR | CSERIAL_THREAD | 0x00000002),			// 既にスレッドが開始している
	RESULT_CSERIAL_THREAD_ERROR_THREAD_START					= (RESULT_ERROR | CSERIAL_THREAD | 0x00000003),			// スレッド開始に失敗しました
	RESULT_CSERIAL_THREAD_ERROR_THREAD_NOT_ACTIVE				= (RESULT_ERROR | CSERIAL_THREAD | 0x00000004),			// スレッド開始に失敗しました
	RESULT_CSERIAL_THREAD_ERROR_SERIAL_OPEN_ALREADY				= (RESULT_ERROR | CSERIAL_THREAD | 0x00000005),			// 既にシリアルオープン
	RESULT_CSERIAL_THREAD_ERROR_SERIAL_OPEN						= (RESULT_ERROR | CSERIAL_THREAD | 0x00000006),			// シリアルオープンに失敗しました
	RESULT_CSERIAL_THREAD_ERROR_SERIAL_SET_ATTRIBUTE			= (RESULT_ERROR | CSERIAL_THREAD | 0x00000007),			// シリアルの属性設定に失敗しました
	RESULT_CSERIAL_THREAD_ERROR_SERIAL_SET_BAUDRATE				= (RESULT_ERROR | CSERIAL_THREAD | 0x00000008),			// シリアルのボーレート設定に失敗しました
	RESULT_CSERIAL_THREAD_ERROR_SYSTEM							= (RESULT_ERROR | CSERIAL_THREAD | 0x00009999),			// システムエラー

	// CSerialRecvThreadのエラー
	RESULT_CSERIAL_RECV_THREAD_ERROR_INIT						= (RESULT_ERROR | CSERIAL_RECV_THREAD | 0x00000001),	// 初期処理に失敗している
	RESULT_CSERIAL_RECV_THREAD_ERROR_THREAD_ALREADY_STARTED		= (RESULT_ERROR | CSERIAL_RECV_THREAD | 0x00000002),	// 既にスレッドが開始している
	RESULT_CSERIAL_RECV_THREAD_ERROR_THREAD_START				= (RESULT_ERROR | CSERIAL_RECV_THREAD | 0x00000003),	// スレッド開始に失敗しました
	RESULT_CSERIAL_RECV_THREAD_ERROR_THREAD_NOT_ACTIVE			= (RESULT_ERROR | CSERIAL_RECV_THREAD | 0x00000004),	// スレッド開始に失敗しました
	RESULT_CSERIAL_RECV_THREAD_ERROR_SYSTEM						= (RESULT_ERROR | CSERIAL_RECV_THREAD | 0x00009999),	// システムエラー












} RESULT_HEADER_ENUM;
